---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onehq-pipelines
secrets:
  - name: machinehq-github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onehq-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- kind: ServiceAccount
  name: onehq-pipelines
  namespace: onehq-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onehq-pipelines-scc-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sccadmin
subjects:
- kind: ServiceAccount
  name: onehq-pipelines
  namespace: onehq-pipelines
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sccadmin
rules:
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
  - verbs:
      - '*'
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onehq-platform-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: hq-platform

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-pipelineruns
rules:
  - verbs:
      - create
    apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rerun-pipeline
  namespace: agencieshq-master-pipeline
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: hq-product
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-pipelineruns
